# Lab Safety

by Jess Grembi

Safety, health, and environmental stewardship are priorities at Penn State.  In particular, our lab handles samples that could potentially contain BSL2 organisms - these are pathogens that can cause diarrheal illness that is self-limiting (not life threatening).  We do not want to get ourselves or others sick so we adhere to strict protocols to reduce exposure when working in the lab.

The [Environmental Health and Safety (EHS)](https://ehs.psu.edu/) team at PSU is a resource to help labs ensure we are in compliance with Federal and State laws, University directives, and are doing our best to support safety, health, and environmental stewardship.  If you have any questions about these topics, feel free to reach out to Dr. Grembi or the lab Safety Officer.  If we can’t answer your question, we can reach out to EHS for their assistance.

***The lab Safety Officer is Pablo Ochoa-Andersen***

## Key points regarding safety:

- Appropriate lab attire includes closed toe shoes and long pants.

- Do not keep food or drink in the lab area.

- Wash your hands before and after conducting lab work.

- Gloves are not worn when opening doors or touching objects that may spread contamination to others.

- All gloves are permeable and will eventually allow chemicals and biological agents to come into contact with your skin.  Thus, double glove if you plan to work with any harsh chemicals and replace gloves as soon as feasible after they become contaminated.

- When using Biosafety cabinets ensure that you are not restricting airflow (with your body or with equipment placed into the cabinet).


## Required Institutional Lab Safety Training 

There are several required trainings before anyone can work in the lab.  Please ensure you have completed all trainings ***and provided certificates to the Lab Safety Officer*** before performing any work in the lab. 

### The following trainings can be accessed from the [EHS training website](https://ehs.psu.edu/training)

- Hazard Communication (HazCom) Training
- Laboratory and Research Safety Training (initial and then annual refresher)
- Biosafety cabinet training
- Regulated Medical Waste
- Spill Prevention and Response
- Compressed gas training (if using the Coy)
- Autoclave Safety (if using the autoclave)

### Our lab is a Biosafety Level 2 (BSL2) lab, which requires the following trainings that can be accessed from the [CITI website](https://citi.psu.edu/)
- Yearly Biosafety training
- Bloodborne Pathogens - Research Personnel

### Since we work with Bloodborne Pathogens, everyone working in the lab needs to be offered updated Hepatitis B vaccination
- The Bloodborne Pathogen Immunization Determination form can be found [here](https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://ehs.psu.edu/sites/ehs/files/immunizationdetermination.doc&ved=2ahUKEwjktPLn3JuOAxVVKlkFHRmKLBgQFnoECBcQAQ&usg=AOvVaw1VFj5u8sX_YtMgqAmODOI2)
- This needs to be sent to Occupational Medicine, a normal course is two vaccinations one month apart


## Lab Safety Tour and site-specific hazard identification

Prior to conducting any work in the lab, new members will be given a lab safety tour by the Safety Officer where you will be shown the major hazards in the lab, and introduced to our lab-specific safety protocols. The safety tour will conclude with a review the Unit Specific Plan, and you will be asked to sign that you understand the hazards present in the lab and the protocols in place to minimize risk.


## Lab Safety Officer Responsibilities

- Serve as the Chemical Safety Officer (CHO)
- Weekly Hazardous waste accumulation point check
- Weekly eyewash station inspection and testing (verify with Huck if they do this or if we need to?)
- Monthly safety inspections
